<?php

namespace ContactBoxBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
    public function findByLastName($lastName) {
        $dql = "SELECT person FROM ContactBoxBundle:Person person
                                    WHERE person.lastName LIKE :lastName ORDER BY person.lastName ASC";
        $query = $this->getEntityManager()->createQuery($dql)
                ->setParameter('lastName', ('%'.$lastName.'%'));
        $contacts = $query->getResult();
        return $contacts;
    }
}
