<?php

namespace ContactBoxBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
    public function findByFirstOrLastName($string) {
        
        $qb = $this->createQueryBuilder('p');
        
        return $qb->where($qb->expr()
                ->orX(
                        $qb->expr()->like('p.firstName', ':string'),
                        $qb->expr()->like('p.lastName', ':string')
                        )
                )
                ->setParameter('string', ('%'.$string.'%'))
                ->orderBy('p.lastName', 'ASC')
                ->getQuery()
                ->getResult();
    }
}
